// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'edb375b0c89a7c599b66f4145d53c326e4d621146af66a47c351b4946bb25c84'>;
export type ExecutionHash =
  ExecutionHashBase<'9d994664e53b1217542f540b460796ef19b63a6d2b7dcbb637ea68e54125990e'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date@1': {
        readonly output: 'pg/date@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time@1': {
        readonly output: 'pg/time@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp@1': {
        readonly output: 'pg/timestamp@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz@1': {
        readonly output: 'pg/timestamptz@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/timestamp@1': {
        readonly output: 'sql/timestamp@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date@1': {
        readonly output: 'pg/date@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time@1': {
        readonly output: 'pg/time@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp@1': {
        readonly output: 'pg/timestamp@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz@1': {
        readonly output: 'pg/timestamptz@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/timestamp@1': {
        readonly output: 'sql/timestamp@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Category: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Location: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Product: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly minStock: CodecTypes['pg/int4@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'];
      readonly cost: CodecTypes['pg/numeric@1']['output'] | null;
      readonly unit: CodecTypes['pg/text@1']['output'] | null;
      readonly categoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly supplierId: CodecTypes['pg/int4@1']['output'] | null;
      readonly locationId: CodecTypes['pg/int4@1']['output'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Supplier: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Tenant: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: 'owner' | 'admin' | 'employee';
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Category: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Location: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Product: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly minStock: CodecTypes['pg/int4@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly cost: CodecTypes['pg/numeric@1']['input'] | null;
      readonly unit: CodecTypes['pg/text@1']['input'] | null;
      readonly categoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly supplierId: CodecTypes['pg/int4@1']['input'] | null;
      readonly locationId: CodecTypes['pg/int4@1']['input'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Supplier: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Tenant: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: 'owner' | 'admin' | 'employee';
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly category: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly location: {
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly product: {
      readonly categoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly cost: CodecTypes['pg/numeric@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly locationId: CodecTypes['pg/int4@1']['output'] | null;
      readonly minStock: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly price: CodecTypes['pg/numeric@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly supplierId: CodecTypes['pg/int4@1']['output'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly unit: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly supplier: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly tenant: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: 'owner' | 'admin' | 'employee';
      readonly tenantId: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly category: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly location: {
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly product: {
      readonly categoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly cost: CodecTypes['pg/numeric@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly locationId: CodecTypes['pg/int4@1']['input'] | null;
      readonly minStock: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly supplierId: CodecTypes['pg/int4@1']['input'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly unit: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly supplier: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly tenant: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: 'owner' | 'admin' | 'employee';
      readonly tenantId: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly category: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['tenantId', 'name'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'category_tenantId_idx_c93ed4f1';
                  readonly prefix: 'category_tenantId_idx';
                  readonly columns: readonly ['tenantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'category';
                    readonly columns: readonly ['tenantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly location: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly code: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['tenantId', 'code'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'location_tenantId_idx_c93ed4f1';
                  readonly prefix: 'location_tenantId_idx';
                  readonly columns: readonly ['tenantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'location';
                    readonly columns: readonly ['tenantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly product: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly stock: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly minStock: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly price: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly cost: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly unit: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly categoryId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly supplierId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly locationId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly tenantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'product_tenantId_idx_c93ed4f1';
                  readonly prefix: 'product_tenantId_idx';
                  readonly columns: readonly ['tenantId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_categoryId_idx_15c304f2';
                  readonly prefix: 'product_categoryId_idx';
                  readonly columns: readonly ['categoryId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_supplierId_idx_c4d9a8b9';
                  readonly prefix: 'product_supplierId_idx';
                  readonly columns: readonly ['supplierId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'product_locationId_idx_7aae3038';
                  readonly prefix: 'product_locationId_idx';
                  readonly columns: readonly ['locationId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'product';
                    readonly columns: readonly ['categoryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'category';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'product';
                    readonly columns: readonly ['supplierId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'supplier';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'product';
                    readonly columns: readonly ['locationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'location';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'product';
                    readonly columns: readonly ['tenantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly supplier: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tenantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'supplier_tenantId_idx_c93ed4f1';
                  readonly prefix: 'supplier_tenantId_idx';
                  readonly columns: readonly ['tenantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'supplier';
                    readonly columns: readonly ['tenantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly tenant: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tenantId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [
                {
                  readonly name: 'user_tenantId_idx_c93ed4f1';
                  readonly prefix: 'user_tenantId_idx';
                  readonly columns: readonly ['tenantId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['tenantId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tenant';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly user_role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['owner', 'admin', 'employee'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly tenant: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Tenant';
    };
    readonly user: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'User';
    };
    readonly category: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Category';
    };
    readonly supplier: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Supplier';
    };
    readonly location: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Location';
    };
    readonly product: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Product';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Category: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
            };
            readonly relations: {
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'category';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly tenantId: { readonly column: 'tenantId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Location: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
            };
            readonly relations: {
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['locationId'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'location';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly code: { readonly column: 'code' };
                readonly tenantId: { readonly column: 'tenantId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Product: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly minStock: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                };
              };
              readonly cost: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                };
              };
              readonly unit: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly categoryId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly supplierId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly locationId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Category';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly location: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['locationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly supplier: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Supplier';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['supplierId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'product';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly description: { readonly column: 'description' };
                readonly stock: { readonly column: 'stock' };
                readonly minStock: { readonly column: 'minStock' };
                readonly price: { readonly column: 'price' };
                readonly cost: { readonly column: 'cost' };
                readonly unit: { readonly column: 'unit' };
                readonly categoryId: { readonly column: 'categoryId' };
                readonly supplierId: { readonly column: 'supplierId' };
                readonly locationId: { readonly column: 'locationId' };
                readonly tenantId: { readonly column: 'tenantId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Supplier: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
            };
            readonly relations: {
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['supplierId'];
                };
              };
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'supplier';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly phone: { readonly column: 'phone' };
                readonly email: { readonly column: 'email' };
                readonly tenantId: { readonly column: 'tenantId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Tenant: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
            };
            readonly relations: {
              readonly categories: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Category';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
              readonly locations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Location';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
              readonly suppliers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Supplier';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
              readonly users: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tenantId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tenant';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly slug: { readonly column: 'slug' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly tenantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int4@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz@1';
                };
              };
            };
            readonly relations: {
              readonly tenant: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Tenant';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tenantId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly tenantId: { readonly column: 'tenantId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly user_role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'owner'; readonly value: 'owner' },
              { readonly name: 'admin'; readonly value: 'admin' },
              { readonly name: 'employee'; readonly value: 'employee' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'category';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'location';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'product';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'supplier';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'tenant';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
